# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('documents', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageDailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_date', models.DateField()),
                ('chat_turns', models.BigIntegerField()),
                ('prompt_tokens', models.BigIntegerField()),
                ('completion_tokens', models.BigIntegerField()),
                ('storage_bytes', models.BigIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_daily_aggregates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'usage_daily_aggregate',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('chat_turn', 'chat_turn'), ('prompt_tokens', 'prompt_tokens'), ('completion_tokens', 'completion_tokens'), ('storage_bytes', 'storage_bytes'), ('api_call', 'api_call')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=128, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('extra', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='conversations.conversation')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'usage_event',
                'indexes': [models.Index(fields=['tenant_id'], name='usage_event_tenant__7991fb_idx'), models.Index(fields=['occurred_at'], name='usage_event_occurre_7ec242_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagedailyaggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'bucket_date'), name='uniq_usage_daily_tenant_date'),
        ),
    ]
