# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model_key', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=256)),
                ('vector_dimension', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('extra_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'embedding_model',
            },
        ),
        migrations.CreateModel(
            name='FineTuneJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled')], max_length=32)),
                ('dataset_storage_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('log_storage_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('output_model_ref', models.CharField(blank=True, max_length=512, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('evaluation_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fine_tune_job',
            },
        ),
        migrations.CreateModel(
            name='InferenceBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model_key', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=256)),
                ('modality', models.CharField(max_length=32)),
                ('max_context_tokens', models.IntegerField(blank=True, null=True)),
                ('supports_streaming', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('extra_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'base_model',
            },
        ),
        migrations.CreateModel(
            name='TenantModelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_bindings', to='models_registry.inferencebasemodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_bindings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_model_binding',
            },
        ),
        migrations.AddConstraint(
            model_name='inferencebasemodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_key'), name='uniq_base_model_provider_key'),
        ),
        migrations.AddField(
            model_name='finetunejob',
            name='base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_tune_jobs', to='models_registry.inferencebasemodel'),
        ),
        migrations.AddField(
            model_name='finetunejob',
            name='parent_fine_tune_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='models_registry.finetunejob'),
        ),
        migrations.AddField(
            model_name='finetunejob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_tune_jobs', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='embeddingmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_key'), name='uniq_embedding_model_provider_key'),
        ),
    ]
