# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('file_upload', 'file_upload'), ('url_import', 'url_import'), ('api_push', 'api_push')], max_length=32)),
                ('source_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('storage_bucket', models.CharField(blank=True, max_length=128, null=True)),
                ('storage_key', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('size_bytes', models.BigIntegerField()),
                ('content_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], max_length=32)),
                ('index_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], max_length=32)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('chunk_profile_json', models.JSONField(blank=True, null=True)),
                ('extracted_aux_storage_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge_base.knowledgebasesnapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('parse', 'parse'), ('chunk', 'chunk'), ('embed', 'embed'), ('index', 'index'), ('full_pipeline', 'full_pipeline')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled')], max_length=32)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worker_task_id', models.CharField(blank=True, max_length=128, null=True)),
                ('attempt_count', models.IntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingestion_job',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('char_count', models.IntegerField()),
                ('vector_point_id', models.CharField(blank=True, max_length=128, null=True)),
                ('embedding_model_key', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_chunks', to='knowledge_base.knowledgebasesnapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document_chunk',
                'indexes': [models.Index(fields=['tenant_id'], name='document_ch_tenant__4a4c99_idx'), models.Index(fields=['vector_point_id'], name='document_ch_vector__032f6f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_document_chunk_document_index'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id'], name='document_tenant__0a1633_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['knowledge_base_id'], name='document_knowled_d09c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['parse_status'], name='document_parse_s_bf92c0_idx'),
        ),
    ]
