# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_knowledge_bases', models.IntegerField()),
                ('max_documents_total', models.IntegerField()),
                ('max_storage_bytes', models.BigIntegerField()),
                ('max_monthly_chat_turns', models.IntegerField()),
                ('max_monthly_tokens', models.BigIntegerField()),
                ('features', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_review', 'pending_review'), ('active', 'active'), ('suspended', 'suspended'), ('archived', 'archived')], max_length=32)),
                ('contact_email', models.CharField(max_length=255)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.plan')),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField()),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('member', 'member'), ('viewer', 'viewer')], max_length=32)),
                ('created_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to='tenants.useraccount')),
            ],
            options={
                'db_table': 'tenant_membership',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_account'), name='uniq_tenant_membership_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenant_status_2e0f38_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['plan_id'], name='tenant_plan_id_5ac748_idx'),
        ),
    ]
