"""initial schema

Revision ID: 88d91eb48e76
Revises: 
Create Date: 2026-04-08 16:31:46.257558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d91eb48e76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('max_context_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_key', name='uq_base_model_provider_key')
    )
    op.create_table('embedding_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_key', name='uq_embedding_model_provider_key')
    )
    op.create_table('end_user_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('external_user_key', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('preference_json', sa.JSON(), nullable=True),
    sa.Column('tag_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_user_key', name='uq_profile_tenant_user')
    )
    op.create_index(op.f('ix_end_user_profile_tenant_id'), 'end_user_profile', ['tenant_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_knowledge_bases', sa.Integer(), nullable=False),
    sa.Column('max_documents_total', sa.Integer(), nullable=False),
    sa.Column('max_storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_monthly_chat_turns', sa.Integer(), nullable=False),
    sa.Column('max_monthly_tokens', sa.BigInteger(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant_api_credential',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='credential_status'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_index(op.f('ix_tenant_api_credential_tenant_id'), 'tenant_api_credential', ['tenant_id'], unique=False)
    op.create_table('usage_daily_aggregate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket_date', sa.Date(), nullable=False),
    sa.Column('chat_turns', sa.BigInteger(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bucket_date', name='uq_usage_daily_tenant_date')
    )
    op.create_table('usage_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('chat_turn', 'prompt_tokens', 'completion_tokens', 'storage_bytes', 'api_call', name='usage_event_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_event_tenant_id'), 'usage_event', ['tenant_id'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='kb_status'), nullable=False),
    sa.Column('embedding_model_id', sa.BigInteger(), nullable=True),
    sa.Column('embedding_model_key', sa.String(length=128), nullable=True),
    sa.Column('current_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_kb_tenant_name')
    )
    op.create_index(op.f('ix_knowledge_base_tenant_id'), 'knowledge_base', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'active', 'suspended', 'archived', name='tenant_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('conversation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=True),
    sa.Column('user_account_id', sa.BigInteger(), nullable=True),
    sa.Column('end_user_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='conversation_status'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['end_user_profile_id'], ['end_user_profile.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_tenant_id'), 'conversation', ['tenant_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('file_upload', 'url_import', 'api_push', name='doc_source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_bucket', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='parse_status'), nullable=False),
    sa.Column('index_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='index_status'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('chunk_profile_json', sa.JSON(), nullable=True),
    sa.Column('extracted_aux_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_table('knowledge_base_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='entry_status'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entry_tenant_id'), 'knowledge_entry', ['tenant_id'], unique=False)
    op.create_table('tenant_membership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_account_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('tenant_model_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('base_model_id', sa.BigInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_model_id'], ['base_model.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('used_base_model_id', sa.BigInteger(), nullable=True),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('pipeline_trace', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('retrieval_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_msg_conv_seq')
    )
    op.create_index(op.f('ix_chat_message_tenant_id'), 'chat_message', ['tenant_id'], unique=False)
    op.create_table('document_chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('vector_point_id', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_key', sa.String(length=128), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_doc_chunk_idx')
    )
    op.create_index(op.f('ix_document_chunk_tenant_id'), 'document_chunk', ['tenant_id'], unique=False)
    op.create_table('ingestion_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.Enum('parse', 'chunk', 'embed', 'index', 'full_pipeline', name='ingestion_job_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='ingestion_job_status'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('worker_task_id', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_job_tenant_id'), 'ingestion_job', ['tenant_id'], unique=False)
    op.create_table('knowledge_entry_chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('vector_point_id', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_key', sa.String(length=128), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_entry_id'], ['knowledge_entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_entry_id', 'chunk_index', name='uq_entry_chunk_idx')
    )
    op.create_index(op.f('ix_knowledge_entry_chunk_tenant_id'), 'knowledge_entry_chunk', ['tenant_id'], unique=False)
    op.create_table('conversation_memory_chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('vector_point_id', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_chunk_tenant_id'), 'conversation_memory_chunk', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memory_chunk_tenant_id'), table_name='conversation_memory_chunk')
    op.drop_table('conversation_memory_chunk')
    op.drop_index(op.f('ix_knowledge_entry_chunk_tenant_id'), table_name='knowledge_entry_chunk')
    op.drop_table('knowledge_entry_chunk')
    op.drop_index(op.f('ix_ingestion_job_tenant_id'), table_name='ingestion_job')
    op.drop_table('ingestion_job')
    op.drop_index(op.f('ix_document_chunk_tenant_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    op.drop_index(op.f('ix_chat_message_tenant_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('tenant_model_binding')
    op.drop_table('tenant_membership')
    op.drop_index(op.f('ix_knowledge_entry_tenant_id'), table_name='knowledge_entry')
    op.drop_table('knowledge_entry')
    op.drop_table('knowledge_base_snapshot')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_conversation_tenant_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_knowledge_base_tenant_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_usage_event_tenant_id'), table_name='usage_event')
    op.drop_table('usage_event')
    op.drop_table('usage_daily_aggregate')
    op.drop_index(op.f('ix_tenant_api_credential_tenant_id'), table_name='tenant_api_credential')
    op.drop_table('tenant_api_credential')
    op.drop_table('plan')
    op.drop_index(op.f('ix_end_user_profile_tenant_id'), table_name='end_user_profile')
    op.drop_table('end_user_profile')
    op.drop_table('embedding_model')
    op.drop_table('base_model')
    # ### end Alembic commands ###
