# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('models_registry', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system'), ('tool', 'tool')], max_length=32)),
                ('content', models.TextField()),
                ('rewritten_query', models.TextField(blank=True, null=True)),
                ('pipeline_trace', models.JSONField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('retrieval_refs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=32)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='EndUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_key', models.CharField(max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('preference_json', models.JSONField(blank=True, null=True)),
                ('tag_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_profiles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'end_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ConversationMemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('vector_point_id', models.CharField(blank=True, max_length=128, null=True)),
                ('embedding_model_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chunks', to='conversations.conversation')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_chunks', to='conversations.chatmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memory_chunks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conversation_memory_chunk',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='end_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.enduserprofile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='knowledge_base.knowledgebase'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='tenants.useraccount'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='used_base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='models_registry.inferencebasemodel'),
        ),
        migrations.AddConstraint(
            model_name='enduserprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_user_key'), name='uniq_end_user_profile_tenant_external_key'),
        ),
        migrations.AddIndex(
            model_name='conversationmemorychunk',
            index=models.Index(fields=['tenant_id'], name='conversatio_tenant__1ebcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemorychunk',
            index=models.Index(fields=['conversation_id'], name='conversatio_convers_114777_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant_id'], name='conversatio_tenant__6b5481_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_account_id'], name='conversatio_user_ac_976758_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_888aec_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['tenant_id'], name='chat_messag_tenant__0d4eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation_id'], name='chat_messag_convers_1d5c10_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='uniq_chat_message_conversation_sequence'),
        ),
    ]
