# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked')], max_length=32)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_api_credential',
                'indexes': [models.Index(fields=['tenant_id'], name='tenant_api__tenant__6fc503_idx')],
            },
        ),
    ]
