# Generated by Django 4.2.7 on 2026-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_registry', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32)),
                ('embedding_model_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kb_snapshots', to='tenants.useraccount')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_base_snapshot',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='knowledge_base.knowledgebase')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='knowledge_base.knowledgebasesnapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'knowledge_entry',
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_bases', to='knowledge_base.knowledgebasesnapshot'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to='models_registry.embeddingmodel'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='KnowledgeEntryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('char_count', models.IntegerField()),
                ('vector_point_id', models.CharField(blank=True, max_length=128, null=True)),
                ('embedding_model_key', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('knowledge_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgeentry')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entry_chunks', to='knowledge_base.knowledgebasesnapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entry_chunks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'knowledge_entry_chunk',
                'indexes': [models.Index(fields=['tenant_id'], name='knowledge_e_tenant__08ab3a_idx'), models.Index(fields=['vector_point_id'], name='knowledge_e_vector__b0acec_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgeentrychunk',
            constraint=models.UniqueConstraint(fields=('knowledge_entry', 'chunk_index'), name='uniq_knowledge_entry_chunk_entry_index'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_knowledge_base_tenant_name'),
        ),
    ]
